reporting: "off"
update:
  method: never
gui:
  showFileTree: true
  nerdFontsVersion: 3
  branchColorPatterns:
    '^(develop|main|master)': '#f2e0aa'
    '^feature/': '#afb4fa'
    '^bugfix/': '#e1859f'
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} {{filename}}'
  editAtLineAndWait: 'nvim --remote-wait +{{line}} {{filename}}'
  editInTerminal: true
git:
  autoFetch: false
  autoRefresh: false
  pagers:
    - externalDiffCommand: difft --color=always
    - colorArg: always
      pager: delta --paging=never
  commitPrefix:
    - pattern: "^\\w+\\/(ECACP-\\d+).*"
      replace: '$1 '
  commit:
    autoWrapCommitMessage: false
mainBranches:
  - develop
  - master
  - main
