#!/bin/bash

# https://github.com/koekeishiya/yabai/wiki/Configuration#configuration-file

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config window_gap 12
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config right_padding 8
yabai -m config left_padding 8

# mouse settings
# yabai -m config mouse_follows_focus on
# yabai -m config mouse_modifier alt
# left click and drag
# yabai -m config mouse_action1 move
# right click and drag
# yabai -m config mouse_action2 resize
# yabai -m config mouse_drop_action swap

# disable yabai for these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off

# yabai -m space 1 --label terminal
# yabai -m space 2 --label browser
# yabai -m space 3 --label misc
# yabai -m space 4 --label notes
#
# # move to space on start
# yabai -m rule --add app="^WezTerm$" space=terminal
# yabai -m rule --add app="^Safari|Arc$" space=browser
# yabai -m rule --add app="^Obsidian$" space=notes
# yabai -m rule --add app=".*" space=misc

yabai -m config external_bar main:34:0
